bugfixes

diff --git a/tasks/setup_debian.yml b/tasks/setup_debian.yml
--- a/tasks/setup_debian.yml
+++ b/tasks/setup_debian.yml
@@ -6,39 +6,11 @@
   connection: local
   vars:
     ansible_python_interpreter: "{{ ansible_playbook_python }}"
-  shell: |
-    cd /tmp || exit 1
-    REPACK=$(fakeroot -u dpkg-repack fastpkg 2>/dev/stdout 1>/dev/null || true)
-    if [ -z "$REPACK" ]; then
-        : # ok
-    elif echo "$REPACK" | grep -q "Identifier removed"; then
-        : # ok
-    else
-        echo "dpkg-repack fastpkg: $REPACK"
-        exit 1
-    fi
-    PACKAGE=$(find . -name "fastpkg_*.deb" 2>/dev/null)
-    if [ -n "$PACKAGE" ]; then
-        mv -f "$PACKAGE" fastpkg.deb || exit 1
-    else
-        echo "file /tmp/fastpkg.deb not found"
-        exit 1
-    fi
+  script: repack-fastpkg.sh
   register: shell_fastpkg_install
   run_once: true
   become: false
-  changed_when: false
-
-- debug:
-    msg: |
-      OUT: {{ shell_fastpkg_install.stdout }}
-      ERR: {{ shell_fastpkg_install.stderr }}
-  when: servermonkey_debug and shell_fastpkg_install.stdout != "" or shell_fastpkg_install.stderr != ""
-
-- name: Fail dpkg-repack
-  fail:
-    msg: "dpkg-repack failed"
-  failed_when: shell_fastpkg_install.stdout != "" or shell_fastpkg_install.stderr != ""
+  changed_when: "not 'skip' in shell_fastpkg_install.stdout"
 
 - name: Copy fastpkg (Debian)
   copy:
@@ -66,15 +38,14 @@
         name:
           - binutils
           - bzip2
-          - cabextract
+          # 'cabextract' will be skipped because it is not on Debian DVD 1
           - cpio
           - lzma
           - p7zip-full
           - rpm
           - unzip
           - xz-utils
-          - python2
-          # 'unshield' will be skipped because it is not in Debian DVD 1
+          # 'unshield' will be skipped because it is not on Debian DVD 1
 
     - name: Find package 'fastpkg-dtrx' in fastpkg repo
       connection: local
@@ -92,10 +63,33 @@
         mode: '0755'
         force: no
 
-    - name: Make dtrx compatible with Python 2 (Posix)
-      replace:
-        path: /usr/local/bin/dtrx
-        regexp: '#!/usr/bin/env python'
-        replace: '#!/usr/bin/env python2'
-      changed_when: false
+    - name: Make dtrx compatible with any Python version
+      shell: |
+        set -e
+        DTRX="/usr/local/bin/dtrx"
+
+        # skip if already set
+        IN_USE=$(grep python <"$DTRX")
+        if echo "$IN_USE" | grep -q python2; then
+            echo "skip, already set to python2"
+            exit 0
+        elif echo "$IN_USE" | grep -q python3; then
+            echo "skip, already set to python3"
+            exit 0
+        fi
+        
+        if [ -x "$(command -v python)" ]; then
+            echo "skip, already compatible"
+        elif [ -x "$(command -v python2)" ]; then
+            echo "set to python2"
+            sed -i 's|^#!/usr/bin/env python$|#!/usr/bin/env python2|' "$DTRX"
+        elif [ -x "$(command -v python3)" ]; then
+            echo "set to python3"
+            sed -i 's|^#!/usr/bin/env python$|#!/usr/bin/env python3|' "$DTRX"
+        else
+            echo "Python is required"
+            exit 1
+        fi
+      register: fastpkg_setup_dtrx_python
+      changed_when: "not 'skip' in fastpkg_setup_dtrx_python.stdout"
   when: not fastpkg_setup_dtrx_installed.stdout
